#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Rodar o phpstan
./vendor/bin/sail php ./vendor/bin/phpstan analyze
if [ $? -ne 0 ]; then
    echo "Atenção! Problema com PHPSTAN. Resolva antes de continuar... 😉";
    exit 1;
fi;

# rodar os testes
./vendor/bin/sail pest --parallel
if [ $? -ne 0 ]; then
    echo "Atenção! Problema com os TESTES. Resolva antes de continuar... 😉";
    exit 1;
fi;


exit 0;
